### ISSUE TITLE
Access to various Dom Objects is missing

### ISSUE THREAD

**Issue by potherca** [Ariadne-CMS/arc-xml#14]

**Comment by poef** [comment]
I've added most DOMElement properties. Still no getElementById, although you can now do:
    $xml->ownerDocument->getElementById('id')
This returns a naked DOMElement, not proxied though. Work continues...

**Comment by potherca** [comment]
Good progress thought :+1:

And I see my description listing the various missing items didn't get saved somehow? :crying_cat_face:

**Comment by poef** [comment]
fixed getElementById as well, check it out.
