### ISSUE TITLE
Docblocks need to be added to the Proxy class

### ISSUE THREAD

**Issue by potherca** [Ariadne-CMS/arc-xml#16]
Auto-discovery of which methods are available is currently missing, because magic is used.

To fix this [`@method` annotations](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/method.html) should be added to the Proxy class(es).

Instead of adding a _huge_ amount of annotations to the class docblock, dockblocks of empty interface(s) could be used instead.

**Comment by poef** [comment]
This should now be fixed in master, please let me know how it works out. (I'll create a new release now)

**Comment by potherca** [comment]
I checked out the PR (#18). Very nice!
